log_level: DEBUG
search_concurrency: 10
search_rate: 10
token_ttl: 1m
words_address: localhost:81
update_address: localhost:82
search_address: localhost:83
api_server:
  address: localhost:80
  timeout: 5s
