// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/petname.proto

package petname

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PetnameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Words         int64                  `protobuf:"varint,1,opt,name=words,proto3" json:"words,omitempty"`
	Separator     string                 `protobuf:"bytes,2,opt,name=separator,proto3" json:"separator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetnameRequest) Reset() {
	*x = PetnameRequest{}
	mi := &file_proto_petname_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetnameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetnameRequest) ProtoMessage() {}

func (x *PetnameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_petname_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetnameRequest.ProtoReflect.Descriptor instead.
func (*PetnameRequest) Descriptor() ([]byte, []int) {
	return file_proto_petname_proto_rawDescGZIP(), []int{0}
}

func (x *PetnameRequest) GetWords() int64 {
	if x != nil {
		return x.Words
	}
	return 0
}

func (x *PetnameRequest) GetSeparator() string {
	if x != nil {
		return x.Separator
	}
	return ""
}

type PetnameStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Words         int64                  `protobuf:"varint,1,opt,name=words,proto3" json:"words,omitempty"`
	Separator     string                 `protobuf:"bytes,2,opt,name=separator,proto3" json:"separator,omitempty"`
	Names         int64                  `protobuf:"varint,3,opt,name=names,proto3" json:"names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetnameStreamRequest) Reset() {
	*x = PetnameStreamRequest{}
	mi := &file_proto_petname_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetnameStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetnameStreamRequest) ProtoMessage() {}

func (x *PetnameStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_petname_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetnameStreamRequest.ProtoReflect.Descriptor instead.
func (*PetnameStreamRequest) Descriptor() ([]byte, []int) {
	return file_proto_petname_proto_rawDescGZIP(), []int{1}
}

func (x *PetnameStreamRequest) GetWords() int64 {
	if x != nil {
		return x.Words
	}
	return 0
}

func (x *PetnameStreamRequest) GetSeparator() string {
	if x != nil {
		return x.Separator
	}
	return ""
}

func (x *PetnameStreamRequest) GetNames() int64 {
	if x != nil {
		return x.Names
	}
	return 0
}

type PetnameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetnameResponse) Reset() {
	*x = PetnameResponse{}
	mi := &file_proto_petname_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetnameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetnameResponse) ProtoMessage() {}

func (x *PetnameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_petname_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetnameResponse.ProtoReflect.Descriptor instead.
func (*PetnameResponse) Descriptor() ([]byte, []int) {
	return file_proto_petname_proto_rawDescGZIP(), []int{2}
}

func (x *PetnameResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_proto_petname_proto protoreflect.FileDescriptor

const file_proto_petname_proto_rawDesc = "" +
	"\n" +
	"\x13proto/petname.proto\x12\apetname\x1a\x1bgoogle/protobuf/empty.proto\"D\n" +
	"\x0ePetnameRequest\x12\x14\n" +
	"\x05words\x18\x01 \x01(\x03R\x05words\x12\x1c\n" +
	"\tseparator\x18\x02 \x01(\tR\tseparator\"`\n" +
	"\x14PetnameStreamRequest\x12\x14\n" +
	"\x05words\x18\x01 \x01(\x03R\x05words\x12\x1c\n" +
	"\tseparator\x18\x02 \x01(\tR\tseparator\x12\x14\n" +
	"\x05names\x18\x03 \x01(\x03R\x05names\"%\n" +
	"\x0fPetnameResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name2\xda\x01\n" +
	"\x10PetnameGenerator\x128\n" +
	"\x04Ping\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x12?\n" +
	"\bGenerate\x12\x17.petname.PetnameRequest\x1a\x18.petname.PetnameResponse\"\x00\x12K\n" +
	"\fGenerateMany\x12\x1d.petname.PetnameStreamRequest\x1a\x18.petname.PetnameResponse\"\x000\x01B Z\x1eyadro.com/course/proto/petnameb\x06proto3"

var (
	file_proto_petname_proto_rawDescOnce sync.Once
	file_proto_petname_proto_rawDescData []byte
)

func file_proto_petname_proto_rawDescGZIP() []byte {
	file_proto_petname_proto_rawDescOnce.Do(func() {
		file_proto_petname_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_petname_proto_rawDesc), len(file_proto_petname_proto_rawDesc)))
	})
	return file_proto_petname_proto_rawDescData
}

var file_proto_petname_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_petname_proto_goTypes = []any{
	(*PetnameRequest)(nil),       // 0: petname.PetnameRequest
	(*PetnameStreamRequest)(nil), // 1: petname.PetnameStreamRequest
	(*PetnameResponse)(nil),      // 2: petname.PetnameResponse
	(*emptypb.Empty)(nil),        // 3: google.protobuf.Empty
}
var file_proto_petname_proto_depIdxs = []int32{
	3, // 0: petname.PetnameGenerator.Ping:input_type -> google.protobuf.Empty
	0, // 1: petname.PetnameGenerator.Generate:input_type -> petname.PetnameRequest
	1, // 2: petname.PetnameGenerator.GenerateMany:input_type -> petname.PetnameStreamRequest
	3, // 3: petname.PetnameGenerator.Ping:output_type -> google.protobuf.Empty
	2, // 4: petname.PetnameGenerator.Generate:output_type -> petname.PetnameResponse
	2, // 5: petname.PetnameGenerator.GenerateMany:output_type -> petname.PetnameResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_petname_proto_init() }
func file_proto_petname_proto_init() {
	if File_proto_petname_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_petname_proto_rawDesc), len(file_proto_petname_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_petname_proto_goTypes,
		DependencyIndexes: file_proto_petname_proto_depIdxs,
		MessageInfos:      file_proto_petname_proto_msgTypes,
	}.Build()
	File_proto_petname_proto = out.File
	file_proto_petname_proto_goTypes = nil
	file_proto_petname_proto_depIdxs = nil
}
