// Code generated by MockGen. DO NOT EDIT.
// Source: ports.go
//
// Generated by this command:
//
//	mockgen -source=ports.go -destination=mocks/isearch_core.go
//

// Package mock_core is a generated GoMock package.
package mock_core

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	core "yadro.com/course/isearch/core"
)

// MockSearcher is a mock of Searcher interface.
type MockSearcher struct {
	ctrl     *gomock.Controller
	recorder *MockSearcherMockRecorder
	isgomock struct{}
}

// MockSearcherMockRecorder is the mock recorder for MockSearcher.
type MockSearcherMockRecorder struct {
	mock *MockSearcher
}

// NewMockSearcher creates a new mock instance.
func NewMockSearcher(ctrl *gomock.Controller) *MockSearcher {
	mock := &MockSearcher{ctrl: ctrl}
	mock.recorder = &MockSearcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSearcher) EXPECT() *MockSearcherMockRecorder {
	return m.recorder
}

// BuildIndex mocks base method.
func (m *MockSearcher) BuildIndex(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildIndex", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// BuildIndex indicates an expected call of BuildIndex.
func (mr *MockSearcherMockRecorder) BuildIndex(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildIndex", reflect.TypeOf((*MockSearcher)(nil).BuildIndex), ctx)
}

// DropIndex mocks base method.
func (m *MockSearcher) DropIndex() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DropIndex")
}

// DropIndex indicates an expected call of DropIndex.
func (mr *MockSearcherMockRecorder) DropIndex() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DropIndex", reflect.TypeOf((*MockSearcher)(nil).DropIndex))
}

// SearchIndex mocks base method.
func (m *MockSearcher) SearchIndex(ctx context.Context, in *core.SearchRequest) (*core.SearchReply, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchIndex", ctx, in)
	ret0, _ := ret[0].(*core.SearchReply)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchIndex indicates an expected call of SearchIndex.
func (mr *MockSearcherMockRecorder) SearchIndex(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchIndex", reflect.TypeOf((*MockSearcher)(nil).SearchIndex), ctx, in)
}

// MockWords is a mock of Words interface.
type MockWords struct {
	ctrl     *gomock.Controller
	recorder *MockWordsMockRecorder
	isgomock struct{}
}

// MockWordsMockRecorder is the mock recorder for MockWords.
type MockWordsMockRecorder struct {
	mock *MockWords
}

// NewMockWords creates a new mock instance.
func NewMockWords(ctrl *gomock.Controller) *MockWords {
	mock := &MockWords{ctrl: ctrl}
	mock.recorder = &MockWordsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWords) EXPECT() *MockWordsMockRecorder {
	return m.recorder
}

// Norm mocks base method.
func (m *MockWords) Norm(ctx context.Context, phrase string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Norm", ctx, phrase)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Norm indicates an expected call of Norm.
func (mr *MockWordsMockRecorder) Norm(ctx, phrase any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Norm", reflect.TypeOf((*MockWords)(nil).Norm), ctx, phrase)
}

// MockDB is a mock of DB interface.
type MockDB struct {
	ctrl     *gomock.Controller
	recorder *MockDBMockRecorder
	isgomock struct{}
}

// MockDBMockRecorder is the mock recorder for MockDB.
type MockDBMockRecorder struct {
	mock *MockDB
}

// NewMockDB creates a new mock instance.
func NewMockDB(ctrl *gomock.Controller) *MockDB {
	mock := &MockDB{ctrl: ctrl}
	mock.recorder = &MockDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDB) EXPECT() *MockDBMockRecorder {
	return m.recorder
}

// GetAllComics mocks base method.
func (m *MockDB) GetAllComics(ctx context.Context) ([]core.DBComic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllComics", ctx)
	ret0, _ := ret[0].([]core.DBComic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllComics indicates an expected call of GetAllComics.
func (mr *MockDBMockRecorder) GetAllComics(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllComics", reflect.TypeOf((*MockDB)(nil).GetAllComics), ctx)
}

// GetComicsByIDs mocks base method.
func (m *MockDB) GetComicsByIDs(ctx context.Context, ids []int) ([]core.DBLightComic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetComicsByIDs", ctx, ids)
	ret0, _ := ret[0].([]core.DBLightComic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetComicsByIDs indicates an expected call of GetComicsByIDs.
func (mr *MockDBMockRecorder) GetComicsByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetComicsByIDs", reflect.TypeOf((*MockDB)(nil).GetComicsByIDs), ctx, ids)
}
