// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/isearch/isearch.proto

package isearch

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Comic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Comic) Reset() {
	*x = Comic{}
	mi := &file_proto_isearch_isearch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comic) ProtoMessage() {}

func (x *Comic) ProtoReflect() protoreflect.Message {
	mi := &file_proto_isearch_isearch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comic.ProtoReflect.Descriptor instead.
func (*Comic) Descriptor() ([]byte, []int) {
	return file_proto_isearch_isearch_proto_rawDescGZIP(), []int{0}
}

func (x *Comic) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Comic) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phrase        string                 `protobuf:"bytes,1,opt,name=phrase,proto3" json:"phrase,omitempty"`
	Limit         int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_proto_isearch_isearch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_isearch_isearch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_proto_isearch_isearch_proto_rawDescGZIP(), []int{1}
}

func (x *SearchRequest) GetPhrase() string {
	if x != nil {
		return x.Phrase
	}
	return ""
}

func (x *SearchRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SearchReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comics        []*Comic               `protobuf:"bytes,1,rep,name=comics,proto3" json:"comics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchReply) Reset() {
	*x = SearchReply{}
	mi := &file_proto_isearch_isearch_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchReply) ProtoMessage() {}

func (x *SearchReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_isearch_isearch_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchReply.ProtoReflect.Descriptor instead.
func (*SearchReply) Descriptor() ([]byte, []int) {
	return file_proto_isearch_isearch_proto_rawDescGZIP(), []int{2}
}

func (x *SearchReply) GetComics() []*Comic {
	if x != nil {
		return x.Comics
	}
	return nil
}

var File_proto_isearch_isearch_proto protoreflect.FileDescriptor

const file_proto_isearch_isearch_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/isearch/isearch.proto\x12\aisearch\x1a\x1bgoogle/protobuf/empty.proto\")\n" +
	"\x05Comic\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"=\n" +
	"\rSearchRequest\x12\x16\n" +
	"\x06phrase\x18\x01 \x01(\tR\x06phrase\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\"5\n" +
	"\vSearchReply\x12&\n" +
	"\x06comics\x18\x01 \x03(\v2\x0e.isearch.ComicR\x06comics2\x82\x01\n" +
	"\aISearch\x128\n" +
	"\x04Ping\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x12=\n" +
	"\vSearchIndex\x12\x16.isearch.SearchRequest\x1a\x14.isearch.SearchReply\"\x00B Z\x1eyadro.com/course/proto/isearchb\x06proto3"

var (
	file_proto_isearch_isearch_proto_rawDescOnce sync.Once
	file_proto_isearch_isearch_proto_rawDescData []byte
)

func file_proto_isearch_isearch_proto_rawDescGZIP() []byte {
	file_proto_isearch_isearch_proto_rawDescOnce.Do(func() {
		file_proto_isearch_isearch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_isearch_isearch_proto_rawDesc), len(file_proto_isearch_isearch_proto_rawDesc)))
	})
	return file_proto_isearch_isearch_proto_rawDescData
}

var file_proto_isearch_isearch_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_isearch_isearch_proto_goTypes = []any{
	(*Comic)(nil),         // 0: isearch.Comic
	(*SearchRequest)(nil), // 1: isearch.SearchRequest
	(*SearchReply)(nil),   // 2: isearch.SearchReply
	(*emptypb.Empty)(nil), // 3: google.protobuf.Empty
}
var file_proto_isearch_isearch_proto_depIdxs = []int32{
	0, // 0: isearch.SearchReply.comics:type_name -> isearch.Comic
	3, // 1: isearch.ISearch.Ping:input_type -> google.protobuf.Empty
	1, // 2: isearch.ISearch.SearchIndex:input_type -> isearch.SearchRequest
	3, // 3: isearch.ISearch.Ping:output_type -> google.protobuf.Empty
	2, // 4: isearch.ISearch.SearchIndex:output_type -> isearch.SearchReply
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_isearch_isearch_proto_init() }
func file_proto_isearch_isearch_proto_init() {
	if File_proto_isearch_isearch_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_isearch_isearch_proto_rawDesc), len(file_proto_isearch_isearch_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_isearch_isearch_proto_goTypes,
		DependencyIndexes: file_proto_isearch_isearch_proto_depIdxs,
		MessageInfos:      file_proto_isearch_isearch_proto_msgTypes,
	}.Build()
	File_proto_isearch_isearch_proto = out.File
	file_proto_isearch_isearch_proto_goTypes = nil
	file_proto_isearch_isearch_proto_depIdxs = nil
}
