// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: proto/isearch/isearch.proto

package isearch

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ISearch_Ping_FullMethodName        = "/isearch.ISearch/Ping"
	ISearch_SearchIndex_FullMethodName = "/isearch.ISearch/SearchIndex"
)

// ISearchClient is the client API for ISearch service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ISearchClient interface {
	Ping(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	SearchIndex(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchReply, error)
}

type iSearchClient struct {
	cc grpc.ClientConnInterface
}

func NewISearchClient(cc grpc.ClientConnInterface) ISearchClient {
	return &iSearchClient{cc}
}

func (c *iSearchClient) Ping(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ISearch_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iSearchClient) SearchIndex(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchReply)
	err := c.cc.Invoke(ctx, ISearch_SearchIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ISearchServer is the server API for ISearch service.
// All implementations must embed UnimplementedISearchServer
// for forward compatibility.
type ISearchServer interface {
	Ping(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	SearchIndex(context.Context, *SearchRequest) (*SearchReply, error)
	mustEmbedUnimplementedISearchServer()
}

// UnimplementedISearchServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedISearchServer struct{}

func (UnimplementedISearchServer) Ping(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedISearchServer) SearchIndex(context.Context, *SearchRequest) (*SearchReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchIndex not implemented")
}
func (UnimplementedISearchServer) mustEmbedUnimplementedISearchServer() {}
func (UnimplementedISearchServer) testEmbeddedByValue()                 {}

// UnsafeISearchServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ISearchServer will
// result in compilation errors.
type UnsafeISearchServer interface {
	mustEmbedUnimplementedISearchServer()
}

func RegisterISearchServer(s grpc.ServiceRegistrar, srv ISearchServer) {
	// If the following call panics, it indicates UnimplementedISearchServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ISearch_ServiceDesc, srv)
}

func _ISearch_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ISearchServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ISearch_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ISearchServer).Ping(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ISearch_SearchIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ISearchServer).SearchIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ISearch_SearchIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ISearchServer).SearchIndex(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ISearch_ServiceDesc is the grpc.ServiceDesc for ISearch service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ISearch_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "isearch.ISearch",
	HandlerType: (*ISearchServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _ISearch_Ping_Handler,
		},
		{
			MethodName: "SearchIndex",
			Handler:    _ISearch_SearchIndex_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/isearch/isearch.proto",
}
